-- ============================================================================
-- C33 Uptime & Reliability Engine: Database Infrastructure
-- JamesTronic Platform
-- ============================================================================
-- Purpose: Monitor system health, log heartbeats, and track incidents.
-- ============================================================================

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE public.monitor_status AS ENUM (
    'operational',
    'degraded',
    'down',
    'maintenance'
);

CREATE TYPE public.monitor_type AS ENUM (
    'database',
    'api',
    'auth',
    'storage',
    'external_service', -- e.g. OpenAI
    'worker'
);

-- ============================================================================
-- TABLES
-- ============================================================================

-- 1. Uptime Monitors: The entities being watched
CREATE TABLE IF NOT EXISTS public.uptime_monitors (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    type public.monitor_type NOT NULL,
    endpoint text, -- optional if internal
    
    current_status public.monitor_status DEFAULT 'operational',
    last_checked_at timestamptz DEFAULT now(),
    last_latency_ms integer DEFAULT 0,
    
    uptime_percentage_24h numeric(5, 2) DEFAULT 100.00,
    
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. Heartbeats: High-volume log of health checks
CREATE TABLE IF NOT EXISTS public.uptime_heartbeats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Bigint for volume
    monitor_id uuid REFERENCES public.uptime_monitors(id) ON DELETE CASCADE,
    
    status public.monitor_status NOT NULL,
    latency_ms integer NOT NULL DEFAULT 0,
    
    created_at timestamptz DEFAULT now() NOT NULL
);

-- 3. System Incidents: Major issues facing users
CREATE TABLE IF NOT EXISTS public.system_incidents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title text NOT NULL,
    description text,
    severity text CHECK (severity IN ('minor', 'major', 'critical')),
    status text CHECK (status IN ('investigating', 'identified', 'monitoring', 'resolved')),
    
    affected_monitors uuid[] DEFAULT '{}', -- Array of monitor IDs
    
    started_at timestamptz DEFAULT now(),
    resolved_at timestamptz,
    
    created_by uuid REFERENCES public.profiles(user_id),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX idx_heartbeats_monitor_date ON public.uptime_heartbeats(monitor_id, created_at DESC);
CREATE INDEX idx_incidents_status ON public.system_incidents(status);

-- ============================================================================
-- RPCs
-- ============================================================================

-- RPC: Record Heartbeat
-- Logs a ping result and updates the monitor's current status cache
CREATE OR REPLACE FUNCTION public.rpc_record_heartbeat(
    p_monitor_id uuid,
    p_status public.monitor_status,
    p_latency_ms integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- 1. Insert Log
    INSERT INTO public.uptime_heartbeats (monitor_id, status, latency_ms)
    VALUES (p_monitor_id, p_status, p_latency_ms);
    
    -- 2. Update Monitor State
    UPDATE public.uptime_monitors
    SET 
        current_status = p_status,
        last_checked_at = now(),
        last_latency_ms = p_latency_ms,
        updated_at = now()
    WHERE id = p_monitor_id;
END;
$$;

-- RPC: Get System Health
-- Returns a summary of all monitors
CREATE OR REPLACE FUNCTION public.rpc_get_system_health()
RETURNS TABLE (
    monitor_id uuid,
    name text,
    type public.monitor_type,
    status public.monitor_status,
    latency_ms integer,
    last_checked_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT 
        id, name, type, current_status, last_latency_ms, last_checked_at
    FROM public.uptime_monitors
    ORDER BY type, name;
$$;

-- ============================================================================
-- SEED DATA
-- ============================================================================

INSERT INTO public.uptime_monitors (name, type, endpoint)
VALUES 
    ('PostgreSQL Database', 'database', 'localhost:5432'),
    ('Supabase Auth', 'auth', '/auth/v1'),
    ('Storage Layer', 'storage', '/storage/v1'),
    ('Qwen AI Gateway', 'external_service', 'https://dashscope.aliyuncs.com'),
    ('Gemini Vision API', 'external_service', 'https://generativelanguage.googleapis.com'),
    ('JamesTronic API', 'api', '/api/v1')
ON CONFLICT DO NOTHING; -- No unique constraint on name, but safeguard if re-run

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE ON public.uptime_monitors TO authenticated;
GRANT SELECT, INSERT ON public.uptime_heartbeats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_incidents TO authenticated;

GRANT ALL ON public.uptime_monitors TO service_role;
GRANT ALL ON public.uptime_heartbeats TO service_role;
GRANT ALL ON public.system_incidents TO service_role;

GRANT EXECUTE ON FUNCTION public.rpc_record_heartbeat TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_system_health TO authenticated;
